version: '3'
services:
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      # 起動スクリプト
      - ./mysql/docker-init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      # - ./mysql/volumes:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - 3306:3306

  go:
    build:
      context: .
      dockerfile: app/Dockerfile
    # command: /bin/sh -c "go run app/main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on: 
      - db